apiVersion: backstage.io/v1alpha1

kind: Component
metadata:
  name: node_backend_boilerplate
  description: Node.js Boilerplate for Back-End using TypeScript
  annotations:
    github.com/project-slug: AlvaroDavi5/Node_BackEnd_Boilerplate-TypeScript
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: alvaro-davi1@hotmail.com
  lifecycle: experimental
