# Docker Compose Version
version: '3.7'

# Containers
services:

  # Application
  app:
    container_name: App_Node
    env_file: ./.env
    # Refered Dockerfile
    build: ./
    #image: node:alpine
    #user: root
    #working_dir: /app
    #command: ['./init.sh']
    networks:
      - default_network
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /node_modules
    depends_on:
      - cache
      - database
      - cloud

  # DataBase
  database:
    container_name: DataBase_PostgreSQL
    image: postgres:latest
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_postgres
    user: root
    volumes:
      # host_path:container_path
      - db_volume:/var/lib/postgresql/
    networks:
      - default_network
    ports:
      - 5432:5432

  # Cloud Services
  cloud:
    container_name: Cloud_LocalStack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,s3,cognito
    networks:
      - default_network
    ports:
      - 4566:4566
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  # Cache
  cache:
    container_name: Cache_Redis
    image: redis:latest
    networks:
      - default_network
    ports:
      - 6379:6379

# Networks for Containers
networks:
  default_network:
    driver: bridge

# Volumes for Containers
volumes:
  db_volume:
    name: db_volume
