# Docker Compose Version
version: "3.7"

# Containers
services:

  # Application
  app:
    container_name: App_Node
    # Refered Dockerfile
    build: ./
    command: yarn run dev
    env_file:
      - ./.env
    user: root
    networks:
      - default_network
    ports:
      - 3000:3000
    volumes:
      # host_path:container_path
      - ./:/home/app/
    depends_on:
      - db
      - cloud
      - cache
    links:
      - db

  # DataBase
  db:
    container_name: DB_PostgreSQL
    image: postgres:latest
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_postgres
    user: root
    networks:
      - default_network
    volumes:
      - db_volume:/var/lib/postgresql/
    ports:
      - 5432:5432

  # Cloud Services
  cloud:
    container_name: Cloud_LocalStack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,s3,cognito
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Cache
  cache:
    container_name: Cache_Redis
    image: redis:latest
    ports:
      - 6379:6379

# Networks for Containers
networks:
  default_network:
    driver: bridge

# Volumes for Containers
volumes:
  db_volume:
    name: db_volume
