# Docker Compose Version
version: '3.7'

# Containers
services:

  # Application
  app:
    container_name: App_Node
    #image: node:alpine
    # Refered Dockerfile
    build: ./
    #user: root
    env_file: ./envs/.env.development.local
    #working_dir: /app
    #command: ['./init.sh']
    ports:
      - 3000:3000
    networks:
      - default_network
    volumes:
      - ./configs:/app/configs
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./yarn.lock:/app/yarn.lock
      - ./init.sh:/app/init.sh
      - /node_modules
    depends_on:
      - cache
      - database
      - cloud

  # DataBase
  database:
    container_name: DataBase_PostgreSQL
    image: postgres:latest
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_postgres
    ports:
      - 5432:5432
    networks:
      - default_network
    volumes:
      # host_path:container_path
      - db_volume:/var/lib/postgresql/

  # Cache
  cache:
    container_name: Cache_Redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default_network

  # Cloud Services
  cloud:
    container_name: Cloud_LocalStack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs,sns,s3,cognito
    ports:
      - 4566:4566
    networks:
      - default_network
    volumes:
      - ${TMPDIR:-/tmp/localstack}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  # Quality
  quality:
    container_name: Quality_SonarQube
    image: sonarqube:latest
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - default_network

# Networks for Containers
networks:
  default_network:
    driver: bridge

# Volumes for Containers
volumes:
  db_volume:
    name: db_volume
