#Backstage Docs
site_name: 'Service Docs'
docs_dir: docs
nav:
  - Home: index.md
  - Architecture: architecture.md
  - System Overview: system-overview.md
  - Tests: testing.md
plugins:
  - techdocs-core
