site_name: Node.js Backend Boilerplate Docs
docs_dir: docs
nav:
  - Home: execution.md
  - Architecture: architecture.md
  - System Overview: system-overview.md
  - Tests: testing.md
plugins:
  - techdocs-core
