analytics:
 reporting_enabled: false

auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: false
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /var/log/loki/boltdb-shipper-compactor

storage_config:
  boltdb_shipper:
    active_index_directory: /var/log/loki/boltdb_shipper/active_index_directory
    cache_location: /var/log/loki/boltdb_shipper/cache
    shared_store: filesystem
  filesystem:
    directory: /var/log/loki/filesystem

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
