server:
  http_listen_port: 9003
  grpc_listen_port: 0

clients:
  - url: http://127.0.0.1:9003/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
