server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://log_monitor:9003/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
    static_configs:
      - targets:
          - log_monitor
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
  - job_name: local
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: local
          __path__: /app/logs.log
