apiVersion: v1

kind: ConfigMap
metadata:
  name: kubeadm-config
  namespace: kube-system
data:
  kubeadm.conf: |
    apiServer:
      certSANs:
      - "master-node"
    controlPlaneEndpoint: "master-node:6443"
    controllerManager:
        extraArgs:
          allocate-node-cidrs: "true"
          cluster-cidr: "10.244.0.0/16"
    networking:
      dnsDomain: "cluster.local"
      podSubnet: "10.244.0.0/16"
    scheduler:
      extraArgs:
        address: "0.0.0.0"
