apiVersion: kind.x-k8s.io/v1alpha4

kind: Cluster
name: boilerplate-cluster
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
# to load Docker image on cluster run: "kind load docker-image -n boilerplate-cluster boilerplate-image:1.0"
