apiVersion: v1

kind: Deployment
metadata:
  name: node-deployment
  namespace: node-boilerplate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boilerplate
  template:
    metadata:
      labels:
        app: boilerplate
    spec:
      containers:
        - name: boilerplate-container
          image: your-boilerplate-image:latest
