apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: node_backend_boilerplate
  description: Node.js Boilerplate for Back-End using TypeScript
  annotations:
    github.com/project-slug: AlvaroDavi5/Node_BackEnd_Boilerplate-TypeScript
    backstage.io/techdocs-ref: dir:../../docs/backstage
  tags:
    - backend
    - node
spec:
  type: service
  lifecycle: experimental
  owner: devs
  system: backend-boilerplate-system
  ci:
    - type: github-actions
      name: ci-pipeline
  providesApis:
    - boilerplate_api
  implementsApis:
    - boilerplate_api
  consumesApis:
    - auth-api
  dependsOn:
    - resource:default/postgres-db
    - component:default/logger-lib

# apiVersion: backstage.io/v1alpha1
# kind: Location
# metadata:
#   name: boilerplate_docs
#   description: Node.js Boilerplate Documentation
# spec:
#   type: url
#   target: ../../docs/backstage
