apiVersion: v1

kind: Secret
metadata:
  name: boilerplate-secrets
  namespace: boilerplate-namespace
  labels:
    name: boilerplate
type: Opaque
data:
  # base64 values
  DB_NAME: ZGJfcG9zdGdyZXM=
  DB_HOST: MTcyLjI1LjAuMQ==
  DB_DBMS_NAME: cG9zdGdyZXM= # postgres
  DB_PORT: NTQzMg==
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cGFzcw==
# add other envs...
