apiVersion: v1

kind: Secret
metadata:
  name: boilerplate-secrets
  namespace: boilerplate-namespace
  labels:
    name: boilerplate
type: Opaque
data:
  DB_NAME: db_postgres
  DB_HOST: 172.25.0.1
  DB_DBMS_NAME: postgres
  DB_PORT: 5432
  DB_USERNAME: postgres
  DB_PASSWORD: pass
