// project definition
Project DB_Example {
  database_type: 'PostgreSQL'
  Note: 'Database documentation example'
}


// tables creation
Table Users as USR {
	id varchar(260) [increment, not null, unique, primary key]
	fullName varchar(100) [not null]
	email varchar(70) [not null]
	password varchar(550) [not null]
	phone varchar(16)
	docType varchar(10)
	document varchar(18)
	fu varchar(2)
	createdAt timestamp [not null, default: `now()`]
	updatedAt timestamp [default: `null`]
	deletedAt timestamp [default: `null`]
	deletedby varchar(260)
}

Table UserPreferences as PREF {
	id varchar(260) [increment, not null, pk]
	userId varchar(260) [not null]
	imagePath varchar(260)
	defaultTheme int
	createdAt timestamp [not null, default: `now()`]
	updatedAt timestamp [default: `null`]
	deletedAt timestamp [default: `null`]
}

// * Entities References
// ? > : Many-to-One
// ? < : One-to-Many
// ? - : One-to-One
Ref: USR.id - PREF.userId [update: cascade, delete: cascade]
