FORMAT: 1A

HOST: http://localhost:3000/api


# API Doc Example

**API Documentation** example.  

by _AlvaroDavi5_
___



# Group API

## Index [/?environment=test]

### Show API Informations [GET]
+ Request
  + Body
    ```json
    {
      "message": "Hi"
    }
    ```
+ Response 200 (application/json)
  + Headers
    ```
    Content-Type: application/json,charset=utf-8
    ETag: "58-4lTdfqkqSvUVMYL4/Ns9oPpdVxo"
    Content-Length: 88
    Vary: Accept-Encoding
    Date: Sat, 02 Apr 2022 19:25:22 GMT
    Connection: keep-alive
    Keep-Alive: timeout=5
    ```
  + Body
    ```json
    {
        "success": true,
        "query": {
            "environment": "test"
        },
        "params": {},
        "hasBody": true,
        "data": {},
        "method": "GET",
        "message": "OK"
    }
    ```
+ Response 401 (application/json)
