// project definition
Project DB_Example {
  database_type: 'PostgreSQL'
  Note: 'Database documentation example'
}


// tables creation
Table users as USR {
	id int [increment, not null, unique, primary key]
	fullName varchar(100) [not null]
	email varchar(70) [not null]
	password varchar(60) [not null]
	phone varchar(16)
	docType varchar(10)
	document varchar(18)
	fu varchar(2)
	createdAt timestamp [not null, default: `now()`]
	updatedAt timestamp [not null, default: `now()`]
}

Table userPreferences as PREF {
	id int [increment, not null, pk]
	userId int [not null]
	imagePath varchar(255)
	defaultTheme int
	createdAt timestamp [not null, default: `now()`]
	updatedAt timestamp [not null, default: `now()`]
}

// entities references
//  > : Many-to-One
//  < : One-to-Many
//  - : One-to-One
Ref: USR.id - PREF.userId [delete: cascade, update: cascade]
