apiVersion: v1

kind: Service
metadata:
  name: boilerplate-service
  namespace: boilerplate-namespace
  labels:
    name: boilerplate
spec:
  selector:
    app: boilerplate-deploy
  type: LoadBalancer # ClusterIP, NodePort, LoadBalancer, ExternalName
  ports:
    - name: app
      protocol: TCP
      port: 3000
      targetPort: 3000
