name: Testing

on:
  push:
    branches: [homolog]
  pull_request:
    branches: [homolog]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  node_build:
    name: Node.js Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Upload Code Coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Installing Dependencies
        run: yarn install

      - name: Checking Dependencies Security
        run: yarn run security-check

      - name: Checking Type
        run: yarn run typecheck

      - name: Building
        run: yarn run build

      - name: Packing
        run: yarn run build:webpack

      - name: Testing Modules
        run: yarn run test:unit
      - name: Testing Integration
        run: yarn run test:integration
      # - name: Testing API
      #   run: yarn run test:e2e

  sonarqube:
    name: SonarQube Analyze

    runs-on: ubuntu-latest

    needs: node_build

    steps:
      - name: Download Code Coverage Results
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Installing Dependencies
        run: yarn install

      - name: Preparing Coverage Files
        run: yarn run sonar:prepare

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master

      - name: SonarQube Quality Gate Check
        id: sonarqube_quality_gate_check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5

      - name: "SonarQube Quality Gate Status Return"
        run: echo "Quality Gate Status -> ${{ steps.sonarqube_quality_gate_check.outputs.quality-gate-status }}"
